name: dev-publish
on:
  push:
    branches: [ dev ]
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: dev
    steps:
      - name: fetch latest
        run: ${{ secrets.SITE_PATH_DEV }}update.sh ${{ secrets.SITE_NAME_DEV }}
          
      - name: restart server
        run: pm2 restart ${{ secrets.SITE_NAME_DEV }}
